name: Test CI

on:

  pull_request:
    branches:
    - master

  push:
    branches:
    - master
    - release/*

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile.test.dockerfile
